### ISSUE TITLE
console output with bad performance warnings

### ISSUE THREAD

**Issue by kromar** [unity3d-jp/MeshSync#347] opened 2021-05-20 22:23 UTC
the console gets filled with this information

fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Repo\\BlenderAddonDevelopment\\development\\src_28\\addons_contrib\\unity_mesh_sync_common.py

**Comment by sindharta** [comment] 2021-05-24 13:30
Thank you.
We noticed this a while back, but unfortunately the priority of this has always been lower in our backlog.
I'll keep this issue open until we fix it.

**Comment by sindharta** [comment] 2021-06-29 13:56
I had a chance to take a look at this this week, and based on what I found, I don't think we can avoid this.

This fake_module approach is "by design" because we want to ensure that we can remove MeshSyncDCCPlugins successfully from Blender via the Preferences UI.
This is the case due to these reasons:

1. The core of MeshSyncDCCPlugin is written in C++ and built into a DLL. The only file that can load this DLL is __init__.py
2. if we put bl_info inside __init__.py, Blender will try to delete the DLL from Blender when we uninstall MeshSyncDCCPlugin. However, python can't unload a DLL, and therefore the uninstallation will always fail with the following error

`PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\MeshSyncClientBlender\\MeshSyncClientBlender.pyd'`

If we put bl_info inside unity_mesh_sync.py outside MeshSyncClientBlender module, then Blender will only remove this py file during the uninstall process while leaving the DLL there. 
This is not perfect, but so far it seems to be the better workflow for installing/uninstalling MeshSyncDCCPlugin for Blender

**Comment by sindharta** [comment] 2021-07-01 08:39
Closing this issue due to the above reason.

**Closed as completed by sindharta** 2021-07-01 08:39 UTC
