### ISSUE TITLE
[MeshSync] Installation error

### ISSUE THREAD

**Issue by Labelpastek** [unity3d-jp/MeshSync#339] opened 2021-03-18 15:57 UTC
I have this error when I click on "Install plugin"
![image](https://user-images.githubusercontent.com/33765612/111652127-1b5a8d80-8807-11eb-9603-1e1bbe1e1da1.png)

`[MeshSync] Installation error. ExitCode: 1. OSError: Python file "D:\Duck" could not be opened: No such file or directory`
The folder name is **"Duck Reaction"** with space. Maybe the path doesn't recognize space in name.

I tried with MeshSync 0.4.0 and 0.7.0 but it doesn't work.
I use Blender 2.90.1 and unity 2020.3.0f1

![image](https://user-images.githubusercontent.com/33765612/111657251-8c03a900-880b-11eb-9dc6-093c0e8341cc.png)

**Comment by sindharta** [comment] 2021-03-19 02:23
Thank you for reporting this.
I have managed to reproduce this bug.

Like you said, it's because the directory has space in it. 

The plugin installation works across multiple Unity projects, so while we are working on the fix, you can create a temporary project in a folder that doesn't have space, and install the plugin using this temporary project.

**Comment by Labelpastek** [comment] 2021-03-19 13:26
Thanks for helping, it works!

**Comment by sindharta** [comment] 2021-03-23 09:27
The error when installing plugin for Blender via a project that has space in its path has been fixed in 0.7.2-preview

**Comment by kromar** [comment] 2021-05-20 22:02
i get this error and my project does not have white spaces in the name. im using untiy 2020 and blender 2.92.  and the 0.7.2 preview package
![image](https://user-images.githubusercontent.com/1472884/119054242-9b4bd200-b9c7-11eb-937c-2f504fda0f95.png)

**Comment by sindharta** [comment] 2021-05-24 13:42
Automatic installation for Blender 2.92 isn't supported yet in 0.7.2-preview.
Please stay tuned for our next update.

**Comment by kromar** [comment] 2021-05-24 14:17
even on blender LTS it wont install, it sits on this installation window for over 5min and im sure it will keep on goin indefinitely
![image](https://user-images.githubusercontent.com/1472884/119361045-83b46800-bcab-11eb-80c1-f8c9f96f489b.png)

**Comment by sindharta** [comment] 2021-05-24 14:26
Can you let me know:

1. The full path to Blender application
2. Your operating system (Windows 10 ?)
3. MeshSync version. I assume it's 0.7.2-preview ?

Also, can you please try the following and see if it helps ?

1. Install Blender in the default path (C:\Program Files\Blender Foundation\Blender 2.83)
2. Restart the computer.

**Comment by kromar** [comment] 2021-05-24 14:50
1. C:\Users\graue\Downloads\blender-2.83.15-windows-x64\blender-2.83.15-stable+blender-v283-release.fd3036520101-windows.amd64-release
2. windows 10
3. 0.7.2-preview (unity 2020.3.4f1)

for the other request, i never use the installation since that messes up the registry and i assume many people do the same. So i can not install it but only move it there for a test. so if you rely on any registry entries that will fail. 
I usually register my version with the command line arguments -r/-R https://docs.blender.org/manual/en/latest/advanced/command_line/arguments.html

Results:
When blender is in that "default folder" the auto detect is working but installation is still not progressing. I get the same problem that a blender command window opens, and the unity progress bar just stays forever.

![image](https://user-images.githubusercontent.com/1472884/119365334-1ce57d80-bcb0-11eb-826a-f430b88b675d.png)

**Comment by sindharta** [comment] 2021-05-25 00:24
Hm, if you can't install it even if Blender is installed in the default location, then the best thing I can do in the next version would be to give better error messages.
Let me reopen this issue.

Just in case, are you behind any firewall, etc ? Because the installation process downloads MeshSyncDCCPlugin package underneath.

**Comment by kromar** [comment] 2021-05-25 19:42
the MeshSyncDCCPlugin seemed to download fine since i extracted the addon from there to get it running so i assume that should not be a issue.
Let me know when you get something to test so i can help getting this resolved.

**Comment by sindharta** [comment] 2021-07-02 08:44
We have just released MeshSync@0.8.0-preview and we have put more detailed error messages there.
Please try it, and let us know what errors you have, if you still have it.

**Comment by sindharta-tanuwijaya** [comment] 2021-07-19 05:09
Closing this issue for now. 
Feel free to reopen this issue, or create a new one if necessary.

**Closed as completed by sindharta-tanuwijaya** 2021-07-19 05:09 UTC
Labels: bug
