### ISSUE TITLE
Can't install Blender 3.2 plugin

### ISSUE THREAD

**Issue by rudijfrake** [unity3d-jp/MeshSync#714] opened 2022-07-15 06:00 UTC
![{D4B7D40F-7823-444D-994A-6432BC4BED8F}](https://user-images.githubusercontent.com/109333960/179160469-617deec2-df32-402a-9f22-f2382eee6263.png)
Not running Blender despite message, fresh restart, Unity 2021.3.6f1 Personal, 0.13.2 preview MeshSync version, Windows 64-bit.

edit: also, when trying to follow the manual installation guide, I can't locate the "Packages/MeshSync DCC Plugins/Editor/Plugins~" path. Where is this?

edit edit: Think I found it in "Library\PackageCache," not "Packages"!

**Comment by sindharta** [comment] 2022-07-19 02:33
The latest version of MeshSync at this moment: 0.13.2-preview, does not support Blender 3.2 yet.
We are planning to add support for this soon, so stay tuned !

**Comment by sindharta** [comment] 2022-07-29 09:25
Can you please try `MeshSync@0.14.2-preview` ?

**Comment by ukn530** [comment] 2022-08-04 02:57
Hello, I tried `MeshSync@0.14.2-preview` with Blender 3.2.1.
But it doen't work for me. Unity 2021.3.7 Apple Sillicon MacBookPro.

There are some errors,
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: mscore assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Unity.MeshSync.Lib.msGetPluginVersionStr()
  at Unity.MeshSync.Lib.GetPluginVersion () [0x00007] in /Users/ukn/Documents/GitHub/MeshSyncTest/Library/PackageCache/com.unity.meshsync@0.14.2-preview/Runtime/Scripts/msCoreAPI.cs:36 
  at Unity.MeshSync.Editor.MeshSyncEditorConstants.MeshSyncEditorConstants_OnLoad () [0x00000] in /Users/ukn/Documents/GitHub/MeshSyncTest/Library/PackageCache/com.unity.meshsync@0.14.2-preview/Editor/Scripts/MeshSyncEditorConstants.cs:13 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <5e2d116f98d140d0a76ec8a673a2a4ac>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <5e2d116f98d140d0a76ec8a673a2a4ac>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <5e2d116f98d140d0a76ec8a673a2a4ac>:0 
  at UnityEditor.EditorAssemblies.ProcessInitializeOnLoadMethodAttributes () [0x000a5] in /Users/bokken/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:147 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadMethodAttributes () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:151)
```

and returns this at every frames when i open the Meshsync preference panel.
```
NullReferenceException: Object reference not set to an instance of an object
Unity.MeshSync.Editor.DCCToolsSettingsTab.IsPackageVersionCompatible (System.String ver0Str, Unity.FilmInternalUtilities.Editor.PackageVersion ver1, Unity.FilmInternalUtilities.Editor.PackageVersion& ver0) (at Library/PackageCache/com.unity.meshsync@0.14.2-preview/Editor/Scripts/UserSettings/DCCToolsSettingsTab.cs:430)
Unity.MeshSync.Editor.DCCToolsSettingsTab.UpdateLatestCompatibleDCCPlugin (UnityEditor.PackageManager.VersionsInfo versionsInfo) (at Library/PackageCache/com.unity.meshsync@0.14.2-preview/Editor/Scripts/UserSettings/DCCToolsSettingsTab.cs:301)
Unity.MeshSync.Editor.DCCToolsSettingsTab.<OnCheckPluginUpdatesButtonClicked>b__12_0 (UnityEditor.PackageManager.Requests.Request`1[T] packageInfo) (at Library/PackageCache/com.unity.meshsync@0.14.2-preview/Editor/Scripts/UserSettings/DCCToolsSettingsTab.cs:284)
Unity.FilmInternalUtilities.Editor.RequestJob`1[T].OnSuccess () (at Library/PackageCache/com.unity.film-internal-utilities@0.15.1-preview/Editor/Scripts/PackageRequest/RequestJob.cs:93)
Unity.FilmInternalUtilities.Editor.RequestJob`1[T].Update () (at Library/PackageCache/com.unity.film-internal-utilities@0.15.1-preview/Editor/Scripts/PackageRequest/RequestJob.cs:80)
Unity.FilmInternalUtilities.Editor.PackageRequestJobManager.UpdateRequestJobs () (at Library/PackageCache/com.unity.film-internal-utilities@0.15.1-preview/Editor/Scripts/PackageRequest/PackageRequestJobManager.cs:182)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)
```

Do you have any ideas?
Can't wait to use your awesome tool. Thank you!

**Comment by sindharta** [comment] 2022-08-04 08:21
Thank you for your report.
We confirmed that MeshSync@0.14.2-preview doesn't work in the Silicon version of Unity 2021.3.x.

Can you please use the Intel version of Unity 2021.3.x for now until we release a fix ?

**Comment by ukn530** [comment] 2022-08-06 08:56
Thanks! it seems to have worked well.
Blender for intel can work, but for the Sillicon dose not.
Windows machine also worked good in this version.

**Comment by sindharta** [comment] 2022-08-08 01:44
Thank you for your confirmation.

**Comment by sindharta** [comment] 2022-08-25 02:50
We just released MeshSync@0.14.3-preview that should work fine for the Silicon version of Unity 2021.3.x.

**Comment by sindharta** [comment] 2022-09-06 03:22
Closing issue since I believe it has been resolved.
Feel free to reopen if necessary.

**Closed as completed by sindharta** 2022-09-06 03:22 UTC
Labels: enhancement

**Comment by LeeSYSU** [comment] 2023-12-14 03:50
- unity version: 2022.3.8f1c1
- mesh sync version: 0.17.3
@sindharta 
![20231214-114448](https://github.com/unity3d-jp/MeshSync/assets/7321934/c839b064-f3e3-4a90-86e9-281a765abced)
