### ISSUE TITLE
URP Lit not working when using InstanceHandling: Instance Renderer

### ISSUE THREAD

**Issue by Wozniax1** [unity3d-jp/MeshSync#775] opened 2022-09-15 10:12 UTC
Hello,

I have errors in the console when trying to use InstanceHandling: Instance Renderer method and URP Lit shader material.
If I set InstanceHandling to Copy material is working.

Error:
`DrawMeshInstanced does not support the shader 'Universal Render Pipeline/Lit' because it does not read any instanced properties. Try switching to DrawMeshInstancedProcedural if the shader is doing procedural instancing.`

**Comment by schinkowski** [comment] 2022-09-20 15:44
Thanks for your feedback @Wozniax1.

Unfortunately this is a regression in some Unity builds and is fixed in Unity 2022.

The meshes should still render correctly and the error should only log a few times, this will not impact performance at runtime because it does not log it at runtime.

If you can't upgrade to Unity 2022 you can work around it by creating a copy of the URP Lit shader and putting `#pragma editor_sync_compilation` in the Material Keywords section and use the modified shader in the material instead.

**Comment by Wozniax1** [comment] 2022-09-20 20:01
Ok Thanks.

Is support for Blender 3.3 and geometry nodes procedural unwraping planned?

**Comment by schinkowski** [comment] 2022-09-21 14:48
Yes, we're looking into blender 3.3 support and geo node UVs should be supported the same way we already support UVs.

**Comment by Wozniax1** [comment] 2022-09-21 15:21
Great, thanks.

**Comment by sindharta** [comment] 2022-11-02 04:40
Closing. 
Feel free to reopen if there are any more related questions.

**Closed as completed by sindharta** 2022-11-02 04:40 UTC
