### ISSUE TITLE
Problems with UV, Normal corruption when switching from Blender to Edit Mode, and MeshSync Server when objects are deleted.

### ISSUE THREAD

**Issue by audtn5742** [unity3d-jp/MeshSync#768] opened 2022-09-03 11:10 UTC
Hello.
Thank you for making a good tool.
If you switch to Edit Mode while using MeshSync in the blender, the normal and UV of the mesh will be ruined.
In addition, when you delete an object, the object that you deleted on the MeshSync Server remains.
It was tested in MeshSync Version 0.14.4, Blender 3.2 Version.
Thank you for your hard work!

**Comment by sindharta** [comment] 2022-09-05 01:28
Thank you for your feedback.
Can you please attach a video or screenshots showing this ?
It will also be great if you can please attach your sample file.

**Comment by audtn5742** [comment] 2022-09-05 03:55
![Meshsync issue 2](https://user-images.githubusercontent.com/46348167/188357475-5cd960b0-b69d-404f-906f-d9b9fbf71289.png)
![Meshsync issue 1](https://user-images.githubusercontent.com/46348167/188357479-d14502ab-beed-4c39-b702-19e1dad85c3b.png)
![Meshsync issue 3](https://user-images.githubusercontent.com/46348167/188357488-28cb73fe-6e30-445c-a3ea-ee39da0f4d55.png)

The problem is occurring like this image.
Thank you for your quick answer!

**Comment by sindharta** [comment] 2022-09-06 03:22
Thank you. We'll investigate this.

**Comment by schinkowski** [comment] 2022-09-09 08:59
Thanks for reporting this @audtn5742.
Unfortunately I cannot reproduce the issue. 
Does this also happen when MeshSync's Auto-Sync is disabled?
What other addons do you have installed?
A short video of it happening would help, too.

**Comment by audtn5742** [comment] 2022-09-10 00:56
Did you create a model and try it with Shade Smooth?
When you create a model, the mesh's normal is broken for each polygon, so there seems to be little difference from the result screen of the problem.
Shade Smooth must be applied to clearly see the difference.
The project file will not be helpful because only Mesh was created in the blender.
The material used in the video was UnityChanToonShader.
The check box is basically made of Unlit Texture material for the built-in check box image.
Disabling Auto-Sync is the same.
I will also share the video I tested and the add-on list I am using, and the link to the video that seems to be happening the same as me.
I hope the video is helpful.

![add-on list](https://user-images.githubusercontent.com/46348167/189462190-959bf180-d737-4beb-ac41-7a169a666e04.png)
![add-on list 2](https://user-images.githubusercontent.com/46348167/189462196-09f3df71-1d25-4af6-91a0-75c62888ab71.png)


https://user-images.githubusercontent.com/46348167/189462084-072b9c92-a65b-46f5-a513-d2cccb53a0f8.mp4

https://youtu.be/_9eUisdFyeo
From 5:50

https://www.bilibili.com/video/BV1rS4y1K7W2/
From 4:30

**Comment by seandillon92** [comment] 2022-11-30 11:35
@audtn5742 we have fixed a bug with broken uv's in edit mode in the latest release (0.16.0-preview). Please let us know if the issues persist

**Comment by audtn5742** [comment] 2022-12-01 05:56
Thank you!
Has the normal broken in edit mode been fixed?

**Comment by seandillon92** [comment] 2022-12-01 12:09
I just had a closer look on the normals and I was able to reproduce the issue. There seems to be some smoothing being applied in edit mode (evident i.e. in inner part of left ear) but its almost as if flat shading is used. I will put it in our backlog, thank you for reporting this.
![normalsIssue2](https://user-images.githubusercontent.com/51912249/205048670-b1714021-3bf6-448b-a905-772c7882b50e.png)

**Comment by sindharta-tanuwijaya** [comment] 2023-02-08 09:42
We found that this issue actually involves several other issues, and we believe all of them have been fixed in `0.17.1-preview`.
Please try it.

**Comment by audtn5742** [comment] 2023-03-15 10:50
Hello
It works fine.
Thank you!
However, when checking the Bake Modifier, the CPU goes up a lot.
On Blender, the Modifire uses Subdivision and Mirror together to do MeshSync, which uses about 70% of the CPU.
Poly was about 30000.
My CPU specification is 13th Gen Intel(R) Core(TM) i9-13900k 3.00 GHz, so I don't think it's lacking.
Is there a solution?

**Comment by sindharta-tanuwijaya** [comment] 2023-03-17 09:10
Hi, this new issue that you are reporting sounds different from the original issue in this thread, so please:
1. Create a new issue describing your new problem
2. Attach a sample file that we can use to reproduce the problem

Thank you.

**Comment by sindharta-tanuwijaya** [comment] 2023-06-12 07:02
Closing issue due non-response.
Please don't hesitate to create a new issue for question/assistance in the future.

**Closed as completed by sindharta-tanuwijaya** 2023-06-12 07:02 UTC
